INSERT INTO groomers (first_name, last_name, address, phone, bio) 
VALUES
    ('Samantha', 'Jones', '123 Main St, Austin TX', '512-555-1234', 'Samantha has been grooming dogs in the Austin area for over 10 years. She specializes in grooming small breeds and is known for her gentle touch.'),
    ('Michael', 'Smith', '456 Oak St, Austin TX', '512-555-5678', 'Michael is a certified groomer with a passion for working with large breeds. He has over 15 years of experience and has groomed dogs for shows and competitions.'),
    ('Emily', 'Davis', '789 Elm St, Austin TX', '512-555-9012', 'Emily has been grooming dogs for 5 years and has a loyal following of clients. She takes a holistic approach to grooming and believes in using natural products.'),
    ('Jonathan', 'Garcia', '1010 Cedar St, Austin TX', '512-555-3456', 'Jonathan is a self-taught groomer who has been grooming dogs for 8 years. He specializes in creative grooming and has won several awards for his designs.'),
    ('Melissa', 'Wilson', '1212 Maple St, Austin TX', '512-555-7890', 'Melissa has been grooming dogs for 3 years and has a passion for rescuing and rehabilitating abused and neglected dogs. She takes a patient and gentle approach to grooming.'),
    ('David', 'Taylor', '1414 Walnut St, Austin TX', '512-555-2345', 'David has been grooming dogs for 7 years and has a reputation for being a calming presence for nervous dogs. He takes his time and uses positive reinforcement techniques.'),
    ('Jessica', 'Brown', '1616 Pine St, Austin TX', '512-555-6789', 'Jessica has been grooming dogs for 4 years and has a background in veterinary medicine. She is skilled in identifying health issues and is dedicated to providing the best care for her clients.'),
    ('Andrew', 'Lee', '1818 Birch St, Austin TX', '512-555-0123', 'Andrew has been grooming dogs for 6 years and has a passion for education. He believes in educating his clients about proper grooming techniques and takes the time to answer any questions they may have.');
